spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
#spring.datasource.url=jdbc:postgresql://localhost:7777/vulnapp
#spring.datasource.username=pgadmin
#spring.datasource.password=C00l_H@cker
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect